@startuml MOVE+

left to right direction

' Atores
actor "Usuário do Sistema" as u
actor "Usuário Comun" as User
actor "Profissional" as Professional
actor "Administrador" as Admin

' Relacionamentos
u <|-- User
User <|-- Professional
u <|-- Admin

package MOVE+ {
    usecase "Receber Notificações" as UC10
    usecase "Gerenciar Perfil" as UC15
    usecase "Alterar Senha" as UC28
    usecase "Alterar Email" as UC29

    usecase "Realizar Login" as UC2
    usecase "Manter Conta" as UC1
    usecase "Acessar Feed de Atualizações" as UC3
    usecase "Enviar Mensagens" as UC8
    usecase "Visualizar Plano de Treino" as UC4
    usecase "Manter Atividades" as UC5
    usecase "Acompanhar Progresso" as UC6
    usecase "Manter Desafios" as UC7
    usecase "Manter Comunidades" as UC9
    usecase "Participar de Comunidades" as UC18
    usecase "Avaliar Profissional" as UC11
    usecase "Manter Eventos" as UC23

    (Personalizar\nPlanos de Treino) as UC19
    (Oferecer\nServiços) as UC20
    (Criar\nAnúncios Personalizados) as UC22

    usecase "Manter Usuários" as UC12
    usecase "Manter Conteúdos" as UC13
    usecase "Gerenciar Anúncios" as UC14
    (Configurar\nPermissões) as UC24
    (Enviar\nNotificações) as UC27

    usecase "Realizar login com google" as UC16
    usecase "Interagir com o Feed" as UC17
}

u -- UC10
u -- UC15

User -- UC1
User -- UC2
User -- UC3
User -- UC4
User -- UC5
User -- UC6
User -- UC7
User -- UC8
User -- UC9
User -- UC11
User -- UC18
User -- UC23

Professional -- UC19
Professional -- UC20
Professional -- UC22

Admin -- UC12
Admin -- UC13
Admin -- UC14
Admin -- UC24
Admin -- UC27

UC2 <.. UC16 : <<extends>>
UC3 <.. UC17 : <<extends>>
UC15 <.. UC28 : <<extends>>
UC15 <.. UC29 : <<extends>>

@enduml